stages:
  train:
    cmd: python model_training.py
    deps:
      - model_training.py
    outs:
      - anomaly_model.pkl
  prediction:
    cmd: python prediction.py
    deps:
      - prediction.py
      - /home/ubuntu/Desktop/e5_anamoly_detection/code/anomaly_detection/anomaly_model.pkl
    outs:
      - Anomalies_detected.csv

